### ISSUE TITLE
Does GTPT-B have the same config and network as GTPT-S?

### ISSUE THREAD

**Issue by Boluo-XD** [haonanwang0522/GTPT#2]
I am comparing the config files and find that the two files are almost the same, I find no difference in the network and my results with GTPT-B are the same as GTPT-S. Is there an error in uploading?
If my checking is not careful, please kindly inform me of the differences
Thank you for your contribution to this work!

**Comment by Boluo-XD** [comment]
In other words, my results using GTPT-B are consistent with GTPT-S in the paper, and I queried the params and FLOPs for GTPT-B and the results are consistent with the paper, so is there something wrong with me?

**Comment by haonanwang0522** [comment]
Thank you for your interest in our work. The model names in config files are different. For example, in experiments/coco_wholebody/gtpt/gtpt_s_256x192_adam_lr1e-3_split2_sigma4.yaml, MODEL.NAME=pose_gtpt_s_wholebody; in experiments/coco_wholebody/gtpt/gtpt_b_256x192_adam_lr1e-3_split2_sigma4.yaml, MODEL.NAME=pose_gtpt_b_wholebody.

**Comment by Boluo-XD** [comment]
Thank you very much for your prompt reply!

My problem at the moment is that my results using GTPT-B don't look like the data in the paper, but they are consistent with the results of GTPT-S. Is this an error or am I running it the wrong way, my running code is as follows:
`CUDA_VISIBLE_DEVICES=0 python tools/train.py --cfg /public/home/bjzhong/home/xdsun/GTPT-main/experiments/coco/gtpt/gtpt_b_256x192_adam_lr1e-3_split2_sigma4.yaml`

and my results is:
![QQ20240924-131446](https://github.com/user-attachments/assets/5a9c1384-f528-467d-9af3-46e0b1bc5571)

Thanks again for your great contribution to this work!

Looking forward to your reply again!

**Comment by haonanwang0522** [comment]
For gtpt-b, we have attained superior performance after only 220 training epochs, without the need to complete the full 300 epochs.

**Comment by Boluo-XD** [comment]
Okay, thanks for the prompt reply! I think it might be a matter of different GPUs, I got very different results with the A100 and the 2080TI, I'm currently re-training with the 2080TI and hopefully I'll get close to the paper's results!

Thanks again for your contribution to this work and for your interest in my problem!

I look forward to your further innovations in this area!
